https://medium.com/@9cv9official/simple-chat-app-using-django-channel-ed5032b79b9c
https://linuxconfig.org/how-to-install-docker-on-ubuntu-20-04-lts-focal-fossa
https://linuxconfig.org/how-to-install-docker-compose-on-ubuntu-20-04-focal-fossa-linux
https://docs.docker.com/engine/install/ubuntu/

https://channels.readthedocs.io/en/latest/tutorial/part_1.html
https://channels.readthedocs.io/en/latest/tutorial/part_2.html
https://channels.readthedocs.io/en/latest/tutorial/part_3.html
https://channels.readthedocs.io/en/latest/tutorial/part_4.html
